### ISSUE TITLE
Missing elisions in PDFs

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-scores#27]

**Comment by craigsapp** [comment]
Should be fixed now.  This is because the `verovio.ttf` file is needed for printing the PDF file (it contains the elision character).  Playing around with using the Simonetta font in the PDFs caused the verovio.ttf font file to be excluded, and therefore the elisions disappeared (Still trying to figure out how to use the Simonetta font in the PDFs which is another issue).
